-- CORE SCHEMA EXECUTION SCRIPT
-- Generated by Database Specialist Agent
-- Execute these commands in your database client

-- 1. Create player_accounts
\i 01_create_player_accounts.sql

-- 2. Create game_sessions
\i 02_create_game_sessions.sql

-- 3. Create session_participants
\i 03_create_session_participants.sql

-- 4. Create characters
\i 04_create_characters.sql

-- 5. Create skills
\i 05_create_skills.sql

-- 6. Create character_skills
\i 06_create_character_skills.sql

-- 7. Create item_templates
\i 07_create_item_templates.sql

-- 8. Create character_inventory
\i 08_create_character_inventory.sql

-- 9. Create abilities
\i 09_create_abilities.sql

-- 10. Create character_abilities
\i 10_create_character_abilities.sql

-- 11. Create guilds
\i 11_create_guilds.sql

-- 12. Create guild_members
\i 12_create_guild_members.sql

-- 13. Create guild_storage
\i 13_create_guild_storage.sql
