-- Create table: player_accounts
-- Generated by Database Specialist Agent
-- File: 01_create_player_accounts.sql

CREATE TABLE IF NOT EXISTS public.player_accounts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL CHECK (char_length(username) >= 3 AND char_length(username) <= 20),
    display_name TEXT CHECK (char_length(display_name) <= 50),
    total_playtime_minutes INTEGER DEFAULT 0 CHECK (total_playtime_minutes >= 0),
    characters_created INTEGER DEFAULT 0 CHECK (characters_created >= 0),
    characters_lost INTEGER DEFAULT 0 CHECK (characters_lost >= 0),
    account_created_at TIMESTAMPTZ DEFAULT NOW(),
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE,
    preferences JSONB DEFAULT '{}',
    CONSTRAINT valid_username CHECK (username ~ '^[a-zA-Z0-9_-]+$')
);
