-- Create table: game_sessions
-- Generated by Database Specialist Agent
-- File: 02_create_game_sessions.sql

CREATE TABLE IF NOT EXISTS public.game_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_name TEXT NOT NULL CHECK (char_length(session_name) >= 1 AND char_length(session_name) <= 100),
    host_player_id UUID REFERENCES public.player_accounts(id) ON DELETE CASCADE,
    max_players INTEGER DEFAULT 8 CHECK (max_players >= 1 AND max_players <= 8),
    current_players INTEGER DEFAULT 0 CHECK (current_players >= 0 AND current_players <= max_players),
    session_status TEXT DEFAULT 'lobby' CHECK (session_status IN ('lobby', 'active', 'paused', 'completed', 'abandoned')),
    difficulty_level TEXT DEFAULT 'normal' CHECK (difficulty_level IN ('easy', 'normal', 'hard', 'elite', 'nightmare')),
    dungeon_floor INTEGER DEFAULT 1 CHECK (dungeon_floor >= 1),
    turn_timer_seconds INTEGER DEFAULT 10 CHECK (turn_timer_seconds >= 5 AND turn_timer_seconds <= 30),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    session_config JSONB DEFAULT '{}',
    CONSTRAINT valid_turn_range CHECK (turn_timer_seconds BETWEEN 5 AND 30)
);
