-- Create table: session_participants
-- Generated by Database Specialist Agent
-- File: 03_create_session_participants.sql

CREATE TABLE IF NOT EXISTS public.session_participants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES public.game_sessions(id) ON DELETE CASCADE,
    player_id UUID REFERENCES public.player_accounts(id) ON DELETE CASCADE,
    character_id UUID, -- Will reference characters table
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    left_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    turn_order INTEGER CHECK (turn_order >= 1 AND turn_order <= 8),
    player_status TEXT DEFAULT 'alive' CHECK (player_status IN ('alive', 'unconscious', 'dead', 'soul_departed', 'disconnected')),
    UNIQUE(session_id, player_id),
    UNIQUE(session_id, turn_order)
);
