-- Create table: characters
-- Generated by Database Specialist Agent
-- File: 04_create_characters.sql

CREATE TABLE IF NOT EXISTS public.characters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_id UUID REFERENCES public.player_accounts(id) ON DELETE CASCADE,
    character_name TEXT NOT NULL CHECK (char_length(character_name) >= 2 AND char_length(character_name) <= 30),
    current_health INTEGER DEFAULT 50 CHECK (current_health >= 0),
    max_health INTEGER DEFAULT 50 CHECK (max_health > 0),
    current_mana INTEGER DEFAULT 25 CHECK (current_mana >= 0),
    max_mana INTEGER DEFAULT 25 CHECK (max_mana >= 0),
    action_points INTEGER DEFAULT 8 CHECK (action_points >= 0 AND action_points <= 12),
    max_action_points INTEGER DEFAULT 8 CHECK (max_action_points >= 6 AND max_action_points <= 12),
    position_x INTEGER DEFAULT 0,
    position_y INTEGER DEFAULT 0,
    facing_direction TEXT DEFAULT 'north' CHECK (facing_direction IN ('north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest')),
    character_status TEXT DEFAULT 'alive' CHECK (character_status IN ('alive', 'unconscious', 'dead', 'soul_departed')),
    death_count INTEGER DEFAULT 0 CHECK (death_count >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_played_at TIMESTAMPTZ DEFAULT NOW(),
    total_playtime_minutes INTEGER DEFAULT 0 CHECK (total_playtime_minutes >= 0),
    is_permadead BOOLEAN DEFAULT FALSE,
    character_data JSONB DEFAULT '{}',
    CONSTRAINT valid_character_name CHECK (character_name ~ '^[a-zA-Z0-9 _-]+$'),
    CONSTRAINT health_constraints CHECK (current_health <= max_health),
    CONSTRAINT mana_constraints CHECK (current_mana <= max_mana),
    CONSTRAINT ap_constraints CHECK (action_points <= max_action_points)
);
