-- Create table: skills
-- Generated by Database Specialist Agent
-- File: 05_create_skills.sql

CREATE TABLE IF NOT EXISTS public.skills (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    skill_name TEXT UNIQUE NOT NULL,
    skill_category TEXT NOT NULL CHECK (skill_category IN ('weapon', 'armor', 'magic', 'combat', 'crafting', 'passive')),
    skill_type TEXT NOT NULL,
    description TEXT NOT NULL,
    max_level INTEGER DEFAULT 100 CHECK (max_level > 0),
    base_training_cost INTEGER DEFAULT 100 CHECK (base_training_cost > 0),
    is_active BOOLEAN DEFAULT TRUE,
    skill_order INTEGER,
    CONSTRAINT unique_skill_order UNIQUE(skill_order)
);
