-- Create table: character_skills
-- Generated by Database Specialist Agent
-- File: 06_create_character_skills.sql

CREATE TABLE IF NOT EXISTS public.character_skills (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    character_id UUID REFERENCES public.characters(id) ON DELETE CASCADE,
    skill_id UUID REFERENCES public.skills(id) ON DELETE CASCADE,
    current_level INTEGER DEFAULT 0 CHECK (current_level >= 0),
    experience_points INTEGER DEFAULT 0 CHECK (experience_points >= 0),
    experience_to_next INTEGER DEFAULT 100 CHECK (experience_to_next > 0),
    times_used INTEGER DEFAULT 0 CHECK (times_used >= 0),
    last_trained_at TIMESTAMPTZ DEFAULT NOW(),
    training_modifier DECIMAL(3,2) DEFAULT 1.00 CHECK (training_modifier > 0),
    UNIQUE(character_id, skill_id),
    CONSTRAINT level_cap CHECK (current_level <= 100)
);
