-- Create table: item_templates
-- Generated by Database Specialist Agent
-- File: 07_create_item_templates.sql

CREATE TABLE IF NOT EXISTS public.item_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    item_name TEXT UNIQUE NOT NULL,
    item_type TEXT NOT NULL CHECK (item_type IN ('weapon', 'armor', 'shield', 'consumable', 'material', 'tool', 'treasure')),
    item_subtype TEXT NOT NULL,
    item_quality TEXT DEFAULT 'common' CHECK (item_quality IN ('poor', 'common', 'uncommon', 'rare', 'epic', 'legendary', 'artifact')),
    base_value INTEGER DEFAULT 1 CHECK (base_value > 0),
    weight DECIMAL(5,2) DEFAULT 1.0 CHECK (weight >= 0),
    durability INTEGER DEFAULT 100 CHECK (durability >= 0),
    required_skills JSONB DEFAULT '[]',
    stat_modifiers JSONB DEFAULT '{}',
    special_properties JSONB DEFAULT '{}',
    description TEXT,
    ascii_symbol CHAR(1) DEFAULT '?',
    color_code TEXT DEFAULT '#FFFFFF',
    is_stackable BOOLEAN DEFAULT FALSE,
    max_stack_size INTEGER DEFAULT 1 CHECK (max_stack_size > 0),
    is_active BOOLEAN DEFAULT TRUE,
    item_order INTEGER,
    CONSTRAINT valid_ascii_symbol CHECK (ascii_symbol ~ '^[!-~]$')
);
