-- Create table: character_inventory
-- Generated by Database Specialist Agent
-- File: 08_create_character_inventory.sql

CREATE TABLE IF NOT EXISTS public.character_inventory (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    character_id UUID REFERENCES public.characters(id) ON DELETE CASCADE,
    item_template_id UUID REFERENCES public.item_templates(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    current_durability INTEGER CHECK (current_durability >= 0),
    is_equipped BOOLEAN DEFAULT FALSE,
    equipment_slot TEXT CHECK (equipment_slot IN ('main_hand', 'off_hand', 'head', 'chest', 'legs', 'feet', 'ring1', 'ring2', 'neck', 'back')),
    custom_properties JSONB DEFAULT '{}',
    acquired_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_equipment_slot UNIQUE(character_id, equipment_slot) DEFERRABLE INITIALLY DEFERRED
);
