-- Create table: abilities
-- Generated by Database Specialist Agent
-- File: 09_create_abilities.sql

CREATE TABLE IF NOT EXISTS public.abilities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ability_name TEXT UNIQUE NOT NULL,
    ability_category TEXT NOT NULL CHECK (ability_category IN ('combat', 'magic', 'stealth', 'utility', 'crafting', 'leadership', 'passive')),
    ability_type TEXT NOT NULL CHECK (ability_type IN ('active', 'passive', 'reactive', 'toggle')),
    ap_cost INTEGER DEFAULT 0 CHECK (ap_cost >= 0 AND ap_cost <= 12),
    mana_cost INTEGER DEFAULT 0 CHECK (mana_cost >= 0),
    cooldown_turns INTEGER DEFAULT 0 CHECK (cooldown_turns >= 0),
    cast_time_ticks INTEGER DEFAULT 1 CHECK (cast_time_ticks >= 0),
    range_tiles INTEGER DEFAULT 1 CHECK (range_tiles >= 0),
    area_of_effect INTEGER DEFAULT 0 CHECK (area_of_effect >= 0),
    required_skills JSONB NOT NULL DEFAULT '[]',
    required_equipment JSONB DEFAULT '[]',
    forbidden_equipment JSONB DEFAULT '[]',
    skill_scaling JSONB DEFAULT '{}',
    base_effects JSONB DEFAULT '{}',
    description TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    ability_order INTEGER,
    CONSTRAINT valid_costs CHECK (ap_cost > 0 OR mana_cost > 0 OR ability_type = 'passive')
);
