-- Create table: character_abilities
-- Generated by Database Specialist Agent
-- File: 10_create_character_abilities.sql

CREATE TABLE IF NOT EXISTS public.character_abilities (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    character_id UUID REFERENCES public.characters(id) ON DELETE CASCADE,
    ability_id UUID REFERENCES public.abilities(id) ON DELETE CASCADE,
    learned_at TIMESTAMPTZ DEFAULT NOW(),
    times_used INTEGER DEFAULT 0 CHECK (times_used >= 0),
    last_used_at TIMESTAMPTZ,
    hotkey_slot INTEGER CHECK (hotkey_slot >= 1 AND hotkey_slot <= 12),
    is_available BOOLEAN DEFAULT TRUE,
    mastery_level INTEGER DEFAULT 1 CHECK (mastery_level >= 1 AND mastery_level <= 10),
    UNIQUE(character_id, ability_id),
    UNIQUE(character_id, hotkey_slot)
);
