-- Create table: guilds
-- Generated by Database Specialist Agent
-- File: 11_create_guilds.sql

CREATE TABLE IF NOT EXISTS public.guilds (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    guild_name TEXT UNIQUE NOT NULL CHECK (char_length(guild_name) >= 3 AND char_length(guild_name) <= 50),
    guild_description TEXT CHECK (char_length(guild_description) <= 500),
    leader_player_id UUID REFERENCES public.player_accounts(id) ON DELETE CASCADE,
    max_members INTEGER DEFAULT 8 CHECK (max_members >= 1 AND max_members <= 8),
    current_members INTEGER DEFAULT 1 CHECK (current_members >= 0 AND current_members <= max_members),
    guild_level INTEGER DEFAULT 1 CHECK (guild_level >= 1),
    guild_experience INTEGER DEFAULT 0 CHECK (guild_experience >= 0),
    guild_treasury INTEGER DEFAULT 0 CHECK (guild_treasury >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    guild_config JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT valid_guild_name CHECK (guild_name ~ '^[a-zA-Z0-9 _-]+$')
);
