-- Create table: guild_members
-- Generated by Database Specialist Agent
-- File: 12_create_guild_members.sql

CREATE TABLE IF NOT EXISTS public.guild_members (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    guild_id UUID REFERENCES public.guilds(id) ON DELETE CASCADE,
    player_id UUID REFERENCES public.player_accounts(id) ON DELETE CASCADE,
    member_role TEXT DEFAULT 'member' CHECK (member_role IN ('leader', 'officer', 'member')),
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    contribution_points INTEGER DEFAULT 0 CHECK (contribution_points >= 0),
    last_active_at TIMESTAMPTZ DEFAULT NOW(),
    member_status TEXT DEFAULT 'active' CHECK (member_status IN ('active', 'inactive', 'suspended')),
    UNIQUE(guild_id, player_id)
);
