-- Create table: guild_storage
-- Generated by Database Specialist Agent
-- File: 13_create_guild_storage.sql

CREATE TABLE IF NOT EXISTS public.guild_storage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    guild_id UUID REFERENCES public.guilds(id) ON DELETE CASCADE,
    item_template_id UUID REFERENCES public.item_templates(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1 CHECK (quantity > 0),
    contributed_by UUID REFERENCES public.player_accounts(id),
    contributed_at TIMESTAMPTZ DEFAULT NOW(),
    storage_type TEXT DEFAULT 'vault' CHECK (storage_type IN ('vault', 'crafting', 'consumables')),
    access_level TEXT DEFAULT 'all' CHECK (access_level IN ('leader', 'officer', 'all')),
    custom_properties JSONB DEFAULT '{}'
);
